using Microsoft.OpenApi;

namespace DotNetOpenApiExtract.Core.Schema;

/// <summary>
/// The schema of one server-sent event written by <c>ServerSentEventsResult&lt;T&gt;</c>, as OpenAPI 3.2
/// describes an event (§4.14.4): an object with a required string <c>data</c>, string <c>event</c> and
/// <c>id</c>, and a non-negative integer <c>retry</c>.
/// </summary>
internal static class SseEventSchema
{
    private const string ServerSentEventsResultFullName = "Microsoft.AspNetCore.Http.HttpResults.ServerSentEventsResult`1";

    /// <summary>
    /// When <paramref name="type"/> is <c>ServerSentEventsResult&lt;T&gt;</c>, returns
    /// <see langword="true"/> and the item type <c>T</c>.
    /// </summary>
    public static bool TryGetItemType(Type type, out Type itemType)
    {
        if (type.IsGenericType && type.GetGenericTypeDefinition().FullName == ServerSentEventsResultFullName)
        {
            itemType = type.GetGenericArguments()[0];
            return true;
        }

        itemType = null!;
        return false;
    }

    /// <summary>
    /// The event schema for items of <paramref name="itemType"/>. The result writes a <c>string</c> or
    /// <c>byte[]</c> item as the data itself, so its <c>data</c> is a plain string; any other item is
    /// JSON serialized with the HTTP JSON options, so <c>data</c> carries
    /// <c>contentMediaType: application/json</c> and a <c>contentSchema</c> generated by
    /// <paramref name="dataGenerator"/> (the generator of that context). A null item is written as
    /// empty data, which the string schema allows.
    /// </summary>
    public static OpenApiSchema Create(Type itemType, SchemaGenerator dataGenerator)
    {
        var data = new OpenApiSchema { Type = JsonSchemaType.String };
        if (!IsWrittenRaw(itemType))
        {
            data.ContentMediaType = "application/json";
            data.ContentSchema = dataGenerator.GenerateSchema(itemType);
        }

        return new OpenApiSchema
        {
            Type = JsonSchemaType.Object,
            Required = new HashSet<string>(StringComparer.Ordinal) { "data" },
            Properties = new Dictionary<string, IOpenApiSchema>(StringComparer.Ordinal)
            {
                ["data"]  = data,
                ["event"] = new OpenApiSchema { Type = JsonSchemaType.String },
                ["id"]    = new OpenApiSchema { Type = JsonSchemaType.String },
                ["retry"] = new OpenApiSchema { Type = JsonSchemaType.Integer, Minimum = "0" },
            },
        };
    }

    private static bool IsWrittenRaw(Type itemType)
    {
        if (itemType.FullName == "System.String")
            return true;

        return itemType.IsArray && itemType.GetElementType()?.FullName == "System.Byte";
    }
}
