using System.Reflection;
using DotNetOpenApiExtract.Core.Discovery;
using DotNetOpenApiExtract.Core.Loading;

namespace DotNetOpenApiExtract.Core.Documentation;

/// <summary>
/// Resolved documentation for an API operation.
/// </summary>
public sealed class OperationDocumentation
{
    /// <summary>Short one-line summary of the operation.</summary>
    public string? Summary { get; init; }

    /// <summary>Longer description of the operation.</summary>
    public string? Description { get; init; }

    /// <summary>Unique identifier for the operation (used in client code generation).</summary>
    public string? OperationId { get; init; }

    /// <summary>Tags used to group operations in the API explorer.</summary>
    public IReadOnlyList<string>? Tags { get; init; }

    /// <summary>Whether the operation is deprecated.</summary>
    public bool Deprecated { get; init; }

    /// <summary>Parameter descriptions by parameter name.</summary>
    public IReadOnlyDictionary<string, string> ParameterDescriptions { get; init; } =
        new Dictionary<string, string>();

    /// <summary>Response descriptions by status code string (e.g. "200").</summary>
    public IReadOnlyDictionary<string, string> ResponseDescriptions { get; init; } =
        new Dictionary<string, string>();
}

/// <summary>
/// Resolved documentation for a schema property.
/// </summary>
public sealed class PropertyDocumentation
{
    /// <summary>Description of the property.</summary>
    public string? Description { get; init; }

    /// <summary>Example value for the property, if present in XML docs.</summary>
    public string? Example { get; init; }
}

/// <summary>
/// Resolves documentation from multiple sources with priority-based fallback chains.
/// Sources are: Swashbuckle Annotations attributes, .NET 9+ ASP.NET Core HTTP attributes,
/// and XML documentation comments generated by the C# compiler.
/// </summary>
public sealed class DocumentationResolver
{
    private readonly XmlDocParser _xmlParser;

    // I4: Cache single-element tag arrays per controller name to avoid per-action allocation.
    private readonly Dictionary<string, string[]> _controllerDefaultTagCache =
        new(StringComparer.Ordinal);

    /// <summary>
    /// Initialises a new <see cref="DocumentationResolver"/>.
    /// </summary>
    /// <param name="xmlParser">
    /// The XML documentation parser to use for XML doc fallbacks.
    /// Must not be null; pass <c>new XmlDocParser(null)</c> for an empty parser.
    /// </param>
    public DocumentationResolver(XmlDocParser xmlParser)
    {
        _xmlParser = xmlParser ?? throw new ArgumentNullException(nameof(xmlParser));
    }

    // =========================================================================
    // Public API
    // =========================================================================

    /// <summary>
    /// Resolve full documentation for an operation (controller action).
    /// </summary>
    /// <remarks>
    /// Fallback chains applied:
    /// <list type="bullet">
    ///   <item>Summary: [SwaggerOperation] → [EndpointSummary] → XML &lt;summary&gt;</item>
    ///   <item>Description: [SwaggerOperation] → [EndpointDescription] → XML &lt;remarks&gt;</item>
    ///   <item>OperationId: [SwaggerOperation] → HTTP attribute Name named arg</item>
    ///   <item>Tags: [SwaggerOperation] → [Tags] → controller name</item>
    ///   <item>Deprecated: presence of [Obsolete] on the method or on the controller class</item>
    ///   <item>ParameterDescriptions: attribute-sourced descriptions merged with XML &lt;param&gt;</item>
    ///   <item>ResponseDescriptions: attribute-sourced descriptions merged with XML &lt;response&gt;</item>
    /// </list>
    /// </remarks>
    /// <param name="action">The action to resolve documentation for.</param>
    /// <returns>A populated <see cref="OperationDocumentation"/> record.</returns>
    public OperationDocumentation ResolveOperation(ActionInfo action)
    {
        ArgumentNullException.ThrowIfNull(action);

        var method = action.Method;
        var xmlDoc = _xmlParser.GetMethodDoc(method);

        var swaggerOp = AttributeHelper.GetAttribute(method, AttributeHelper.Names.SwaggerOperation);

        // --- Summary ---
        string? summary = null;

        // Priority 1: [SwaggerOperation(Summary = "...")]
        if (swaggerOp != null)
            summary = AttributeHelper.GetNamedArgument<string>(swaggerOp, "Summary");

        // Priority 2: [EndpointSummary("...")]
        if (string.IsNullOrEmpty(summary))
        {
            var endpointSummaryAttr = AttributeHelper.GetAttribute(method, AttributeHelper.Names.EndpointSummary);
            if (endpointSummaryAttr != null)
                summary = AttributeHelper.GetConstructorArgument<string>(endpointSummaryAttr, 0);
        }

        // Priority 3: XML <summary>
        if (string.IsNullOrEmpty(summary))
            summary = xmlDoc?.Summary;

        // Normalize empty to null
        if (string.IsNullOrEmpty(summary))
            summary = null;

        // --- Description ---
        string? description = null;

        // Priority 1: [SwaggerOperation(Description = "...")]
        if (swaggerOp != null)
            description = AttributeHelper.GetNamedArgument<string>(swaggerOp, "Description");

        // Priority 2: [EndpointDescription("...")]
        if (string.IsNullOrEmpty(description))
        {
            var endpointDescAttr = AttributeHelper.GetAttribute(method, AttributeHelper.Names.EndpointDescription);
            if (endpointDescAttr != null)
                description = AttributeHelper.GetConstructorArgument<string>(endpointDescAttr, 0);
        }

        // Priority 3: XML <remarks>
        if (string.IsNullOrEmpty(description))
            description = xmlDoc?.Remarks;

        if (string.IsNullOrEmpty(description))
            description = null;

        // --- OperationId ---
        string? operationId = null;

        // Priority 1: [SwaggerOperation(OperationId = "...")]
        if (swaggerOp != null)
            operationId = AttributeHelper.GetNamedArgument<string>(swaggerOp, "OperationId");

        // Priority 2: Named arg "Name" on the HTTP method attribute
        if (string.IsNullOrEmpty(operationId))
            operationId = ResolveHttpAttributeName(method);

        if (string.IsNullOrEmpty(operationId))
            operationId = null;

        // --- Tags ---
        IReadOnlyList<string>? tags = null;

        // Priority 1: [SwaggerOperation(Tags = new[] { "..." })]
        if (swaggerOp != null)
            tags = ResolveSwaggerOperationTags(swaggerOp);

        // Priority 2: [Tags("tag1", "tag2")]  (.NET 9+)
        if (tags == null || tags.Count == 0)
            tags = ResolveTagsAttribute(method);

        // Priority 3: controller name as the default tag.
        // Use a cached single-element array stored on the ControllerInfo (I4).
        if (tags == null || tags.Count == 0)
            tags = GetOrCreateControllerDefaultTag(action.Controller.Name);

        // --- Deprecated ---
        // [Obsolete] on the action method OR on the controller class makes the operation deprecated.
        bool deprecated = AttributeHelper.HasAttribute(method, AttributeHelper.Names.Obsolete)
                       || AttributeHelper.HasAttribute(action.Controller.Type, AttributeHelper.Names.Obsolete);

        // --- ParameterDescriptions ---
        // Merge: attribute-sourced description (already in ActionParameterInfo.Description)
        // is the primary source; XML <param> fills gaps.
        var paramDescriptions = ResolveParameterDescriptions(method, xmlDoc);

        // --- ResponseDescriptions ---
        // Merge: attribute-sourced description (already in ResponseInfo.Description)
        // is the primary source; XML <response> fills gaps.
        var responseDescriptions = ResolveResponseDescriptions(method, xmlDoc);

        return new OperationDocumentation
        {
            Summary = summary,
            Description = description,
            OperationId = operationId,
            Tags = tags,
            Deprecated = deprecated,
            ParameterDescriptions = paramDescriptions,
            ResponseDescriptions = responseDescriptions,
        };
    }

    /// <summary>
    /// Resolve documentation for a schema property.
    /// </summary>
    /// <remarks>
    /// Fallback chain:
    /// <list type="bullet">
    ///   <item>Description: [SwaggerSchema(Description = "...")] → [Description("...")] → XML &lt;summary&gt;</item>
    ///   <item>Example: XML &lt;example&gt; on the property</item>
    /// </list>
    /// </remarks>
    /// <param name="declaringType">The type that declares the property.</param>
    /// <param name="property">The property to resolve documentation for.</param>
    /// <returns>A populated <see cref="PropertyDocumentation"/> record.</returns>
    public PropertyDocumentation ResolveProperty(Type declaringType, PropertyInfo property)
    {
        ArgumentNullException.ThrowIfNull(declaringType);
        ArgumentNullException.ThrowIfNull(property);

        string? description = null;

        // Merged so that [SwaggerSchema] / [Description] applied to a positional-record
        // parameter (default target) are seen, in addition to attributes on the property itself.
        var propertyAttrs = AttributeHelper.GetMergedPropertyAttributes(property);

        // Priority 1: [SwaggerSchema(Description = "...")]
        var swaggerSchema = AttributeHelper.GetAttribute(propertyAttrs, AttributeHelper.Names.SwaggerSchema);
        if (swaggerSchema != null)
            description = AttributeHelper.GetNamedArgument<string>(swaggerSchema, "Description");

        // Priority 2: [Description("...")]  (System.ComponentModel)
        if (string.IsNullOrEmpty(description))
        {
            var descAttr = AttributeHelper.GetAttribute(propertyAttrs, AttributeHelper.Names.Description);
            if (descAttr != null)
                description = AttributeHelper.GetConstructorArgument<string>(descAttr, 0);
        }

        // XML doc keys live under the type that DECLARES the property.
        // For inherited properties this is the base; for overridden properties it's
        // the most-derived type that re-declares them. property.DeclaringType is
        // always the right key — fall back to declaringType only if reflection
        // returned a null DeclaringType (defensive against malformed assemblies).
        var xmlDocOwner = property.DeclaringType ?? declaringType;
        var xmlPropDoc = _xmlParser.GetPropertyDoc(xmlDocOwner, property.Name);

        // Priority 3: XML <summary>
        if (string.IsNullOrEmpty(description))
            description = xmlPropDoc?.Summary;

        if (string.IsNullOrEmpty(description))
            description = null;

        // --- Example ---
        // Sourced from XML <example> on the property
        string? example = null;
        if (xmlPropDoc?.Example != null && !string.IsNullOrEmpty(xmlPropDoc.Example))
            example = xmlPropDoc.Example;

        return new PropertyDocumentation
        {
            Description = description,
            Example = example,
        };
    }

    /// <summary>
    /// Resolve description for a schema type.
    /// </summary>
    /// <remarks>
    /// Fallback chain:
    /// <list type="bullet">
    ///   <item>[SwaggerSchema(Description = "...")] on type</item>
    ///   <item>[Description("...")] on type</item>
    ///   <item>XML &lt;summary&gt; on type</item>
    /// </list>
    /// </remarks>
    /// <param name="type">The type to resolve a description for.</param>
    /// <returns>The resolved description, or <see langword="null"/> if none found.</returns>
    public string? ResolveTypeDescription(Type type)
    {
        ArgumentNullException.ThrowIfNull(type);

        // Priority 1: [SwaggerSchema(Description = "...")]
        var swaggerSchema = AttributeHelper.GetAttribute(type, AttributeHelper.Names.SwaggerSchema);
        if (swaggerSchema != null)
        {
            var desc = AttributeHelper.GetNamedArgument<string>(swaggerSchema, "Description");
            if (!string.IsNullOrEmpty(desc))
                return desc;
        }

        // Priority 2: [Description("...")]  (System.ComponentModel)
        var descAttr = AttributeHelper.GetAttribute(type, AttributeHelper.Names.Description);
        if (descAttr != null)
        {
            var desc = AttributeHelper.GetConstructorArgument<string>(descAttr, 0);
            if (!string.IsNullOrEmpty(desc))
                return desc;
        }

        // Priority 3: XML <summary>
        var xmlDoc = _xmlParser.GetTypeDoc(type);
        var xmlSummary = xmlDoc?.Summary;
        return string.IsNullOrEmpty(xmlSummary) ? null : xmlSummary;
    }

    /// <summary>
    /// Resolve the description for a single enum member value.
    /// </summary>
    /// <remarks>
    /// Fallback chain:
    /// <list type="bullet">
    ///   <item>XML <c>&lt;summary&gt;</c> on the enum field</item>
    ///   <item><c>[Description("...")]</c> attribute on the enum field</item>
    /// </list>
    /// </remarks>
    /// <param name="enumType">The enum type that declares the member.</param>
    /// <param name="memberName">The name of the enum member (e.g. <c>"Active"</c>).</param>
    /// <returns>
    /// The trimmed description text, or an empty string when neither XML doc nor
    /// <c>[Description]</c> is present for the member.
    /// </returns>
    public string ResolveEnumValueDescription(Type enumType, string memberName)
    {
        ArgumentNullException.ThrowIfNull(enumType);
        ArgumentNullException.ThrowIfNull(memberName);

        // Priority 1: XML <summary> on the enum field
        var xmlSummary = _xmlParser.GetFieldDoc(enumType, memberName)?.Summary;
        if (!string.IsNullOrEmpty(xmlSummary))
            return xmlSummary;

        // Priority 2: [Description("...")] on the enum field
        var field = enumType.GetField(memberName, BindingFlags.Public | BindingFlags.Static);
        if (field != null)
        {
            var descAttr = AttributeHelper.GetAttribute(field, AttributeHelper.Names.Description);
            if (descAttr != null)
            {
                var text = AttributeHelper.GetConstructorArgument<string>(descAttr, 0);
                if (!string.IsNullOrEmpty(text))
                    return text;
            }
        }

        return string.Empty;
    }

    /// <summary>
    /// Resolve tag description for a controller.
    /// </summary>
    /// <remarks>
    /// Fallback chain:
    /// <list type="bullet">
    ///   <item><see cref="ControllerInfo.TagDescription"/> (set from [SwaggerTag])</item>
    ///   <item>XML &lt;summary&gt; on the controller class</item>
    /// </list>
    /// </remarks>
    /// <param name="controller">The controller to resolve a tag description for.</param>
    /// <returns>The resolved tag description, or <see langword="null"/> if none found.</returns>
    public string? ResolveTagDescription(ControllerInfo controller)
    {
        ArgumentNullException.ThrowIfNull(controller);

        // Priority 1: [SwaggerTag] — already extracted into ControllerInfo.TagDescription
        if (!string.IsNullOrEmpty(controller.TagDescription))
            return controller.TagDescription;

        // Priority 2: XML <summary> on controller class
        var xmlDoc = _xmlParser.GetTypeDoc(controller.Type);
        var xmlSummary = xmlDoc?.Summary;
        return string.IsNullOrEmpty(xmlSummary) ? null : xmlSummary;
    }

    // =========================================================================
    // Private helpers
    // =========================================================================

    /// <summary>
    /// HTTP verb attribute full names — allocated once as a static field (I5).
    /// </summary>
    private static readonly string[] HttpAttributeFullNames =
    {
        AttributeHelper.Names.HttpGet,
        AttributeHelper.Names.HttpPost,
        AttributeHelper.Names.HttpPut,
        AttributeHelper.Names.HttpDelete,
        AttributeHelper.Names.HttpPatch,
        AttributeHelper.Names.HttpHead,
        AttributeHelper.Names.HttpOptions,
    };

    /// <summary>
    /// Reads the <c>Name</c> named argument from the HTTP method attribute on the given method.
    /// For example, <c>[HttpGet(Name = "GetWidget")]</c> returns "GetWidget".
    /// </summary>
    private static string? ResolveHttpAttributeName(MethodInfo method)
    {
        // Check all HTTP verb attributes for a Name named argument.
        var httpAttributeNames = HttpAttributeFullNames;

        foreach (var attrFullName in httpAttributeNames)
        {
            var attr = AttributeHelper.GetAttribute(method, attrFullName);
            if (attr == null)
                continue;

            var name = AttributeHelper.GetNamedArgument<string>(attr, "Name");
            if (!string.IsNullOrEmpty(name))
                return name;
        }

        return null;
    }

    /// <summary>
    /// Reads the <c>Tags</c> named argument from a <c>[SwaggerOperation]</c> attribute.
    /// The value is a <see cref="IReadOnlyCollection{T}"/> of <see cref="CustomAttributeTypedArgument"/>
    /// because arrays in custom attribute data are boxed in that collection type.
    /// </summary>
    private static IReadOnlyList<string>? ResolveSwaggerOperationTags(CustomAttributeData swaggerOpAttr)
    {
        // Iterate defensively: accessing MemberName on a default CustomAttributeNamedArgument
        // struct from MetadataLoadContext can throw NullReferenceException, so we guard each access.
        CustomAttributeNamedArgument? tagsArgNullable = null;
        foreach (var namedArg in swaggerOpAttr.NamedArguments)
        {
            try
            {
                if (namedArg.MemberName == "Tags")
                {
                    tagsArgNullable = namedArg;
                    break;
                }
            }
            catch (NullReferenceException)
            {
                // MetadataLoadContext can produce default structs whose members throw.
                // Skip this entry.
            }
        }

        if (tagsArgNullable == null)
            return null;

        var tagsArg = tagsArgNullable.Value;

        // The value is an IReadOnlyCollection<CustomAttributeTypedArgument> for array values.
        if (tagsArg.TypedValue.Value is IReadOnlyCollection<CustomAttributeTypedArgument> tagItems)
        {
            var result = new List<string>();
            foreach (var item in tagItems)
            {
                if (item.Value is string s && !string.IsNullOrEmpty(s))
                    result.Add(s);
            }

            return result.Count > 0 ? result : null;
        }

        return null;
    }

    /// <summary>
    /// Reads the constructor arguments of a <c>[Tags("tag1", "tag2", ...)]</c> attribute
    /// (FullName: <c>Microsoft.AspNetCore.Http.TagsAttribute</c>).
    /// The attribute accepts <c>params string[] tags</c> as its single constructor parameter,
    /// which arrives in <see cref="CustomAttributeData"/> as either a nested collection or
    /// individual arguments.
    /// </summary>
    private static IReadOnlyList<string>? ResolveTagsAttribute(MethodInfo method)
    {
        var tagsAttr = AttributeHelper.GetAttribute(method, AttributeHelper.Names.Tags);
        if (tagsAttr == null)
            return null;

        var result = new List<string>();

        // params string[] — may arrive as a single IReadOnlyCollection<CustomAttributeTypedArgument>
        // or as individual string constructor arguments depending on how the compiler emitted it.
        if (tagsAttr.ConstructorArguments.Count == 1)
        {
            var singleArg = tagsAttr.ConstructorArguments[0];

            if (singleArg.Value is IReadOnlyCollection<CustomAttributeTypedArgument> items)
            {
                foreach (var item in items)
                {
                    if (item.Value is string s && !string.IsNullOrEmpty(s))
                        result.Add(s);
                }
            }
            else if (singleArg.Value is string str && !string.IsNullOrEmpty(str))
            {
                result.Add(str);
            }
        }
        else
        {
            // Multiple distinct constructor arguments (unusual but handle defensively).
            foreach (var arg in tagsAttr.ConstructorArguments)
            {
                if (arg.Value is string s && !string.IsNullOrEmpty(s))
                    result.Add(s);
            }
        }

        return result.Count > 0 ? result : null;
    }

    /// <summary>
    /// Builds a parameter-name → description dictionary by combining attribute-sourced
    /// descriptions (from <c>[SwaggerParameter]</c> and <c>[Description]</c>, already
    /// resolved in <see cref="Extraction.ParameterExtractor"/>) with XML <c>&lt;param&gt;</c>
    /// docs as a fallback for each parameter not already described.
    /// </summary>
    private static IReadOnlyDictionary<string, string> ResolveParameterDescriptions(
        MethodInfo method,
        XmlDocEntry? xmlDoc)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var param in method.GetParameters())
        {
            var paramName = param.Name;
            if (string.IsNullOrEmpty(paramName))
                continue;

            // Priority 1: [SwaggerParameter] constructor arg 0
            string? description = null;
            var swaggerParam = AttributeHelper.GetAttribute(param, AttributeHelper.Names.SwaggerParameter);
            if (swaggerParam != null)
                description = AttributeHelper.GetConstructorArgument<string>(swaggerParam, 0);

            // Priority 2: [Description] constructor arg 0
            if (string.IsNullOrEmpty(description))
            {
                var descAttr = AttributeHelper.GetAttribute(param, AttributeHelper.Names.Description);
                if (descAttr != null)
                    description = AttributeHelper.GetConstructorArgument<string>(descAttr, 0);
            }

            // Priority 3: XML <param name="...">
            if (string.IsNullOrEmpty(description) && xmlDoc != null)
                xmlDoc.Parameters.TryGetValue(paramName, out description);

            if (!string.IsNullOrEmpty(description))
                result[paramName] = description;
        }

        return result;
    }

    /// <summary>
    /// Builds a status-code → description dictionary by combining attribute-sourced
    /// descriptions (from <c>[SwaggerResponse]</c> and <c>[ProducesResponseType]</c>, already
    /// resolved in <see cref="Extraction.ResponseExtractor"/>) with XML <c>&lt;response&gt;</c>
    /// docs as a fallback for each status code not already described.
    /// </summary>
    private static IReadOnlyDictionary<string, string> ResolveResponseDescriptions(
        MethodInfo method,
        XmlDocEntry? xmlDoc)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        // --- [SwaggerResponse] ---
        foreach (var attr in AttributeHelper.GetAttributes(method, AttributeHelper.Names.SwaggerResponse))
        {
            // Constructor: (int statusCode, string? description, Type? type)
            if (attr.ConstructorArguments.Count < 1)
                continue;

            var statusCode = CastToInt(attr.ConstructorArguments[0].Value);
            if (statusCode == null)
                continue;

            var codeKey = statusCode.Value.ToString();
            if (result.ContainsKey(codeKey))
                continue; // first wins

            if (attr.ConstructorArguments.Count >= 2 &&
                attr.ConstructorArguments[1].Value is string desc &&
                !string.IsNullOrEmpty(desc))
            {
                result[codeKey] = desc;
            }
        }

        // --- [ProducesResponseType] named arg "Description" (.NET 10+) ---
        foreach (var attr in AttributeHelper.GetAttributes(method, AttributeHelper.Names.ProducesResponseType))
        {
            var statusCode = ExtractProducesResponseTypeStatusCode(attr);
            if (statusCode == null)
                continue;

            var codeKey = statusCode.Value.ToString();
            if (result.ContainsKey(codeKey))
                continue;

            var desc = AttributeHelper.GetNamedArgument<string>(attr, "Description");
            if (!string.IsNullOrEmpty(desc))
                result[codeKey] = desc;
        }

        // --- XML <response code="..."> as fallback for any not yet described ---
        if (xmlDoc != null)
        {
            foreach (var kvp in xmlDoc.Responses)
            {
                if (!result.ContainsKey(kvp.Key) && !string.IsNullOrEmpty(kvp.Value))
                    result[kvp.Key] = kvp.Value;
            }
        }

        return result;
    }

    /// <summary>
    /// Extracts the HTTP status code integer from a <c>[ProducesResponseType(...)]</c>
    /// attribute in all its supported overload forms.
    /// Returns null if the status code cannot be determined.
    /// </summary>
    private static int? ExtractProducesResponseTypeStatusCode(CustomAttributeData attr)
    {
        var args = attr.ConstructorArguments;

        if (args.Count == 1)
        {
            // (int statusCode)
            return CastToInt(args[0].Value);
        }

        if (args.Count >= 2)
        {
            // (Type type, int statusCode) — Type first, int second
            var first = args[0];
            var second = args[1];

            if (IsTypeArgument(first) && IsIntArgument(second))
                return CastToInt(second.Value);

            // Defensive: (int statusCode, Type type)
            if (IsIntArgument(first) && IsTypeArgument(second))
                return CastToInt(first.Value);
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Returns a cached single-element string array containing the controller name,
    /// avoiding a new array allocation for every action that uses the default tag (I4).
    /// </summary>
    private string[] GetOrCreateControllerDefaultTag(string controllerName)
    {
        if (!_controllerDefaultTagCache.TryGetValue(controllerName, out var cached))
        {
            cached = new[] { controllerName };
            _controllerDefaultTagCache[controllerName] = cached;
        }
        return cached;
    }

    // -------------------------------------------------------------------------
    // Attribute argument type-check helpers (mirrors ResponseExtractor pattern)
    // -------------------------------------------------------------------------

    private static bool IsIntArgument(CustomAttributeTypedArgument arg)
    {
        var fullName = arg.ArgumentType.FullName;
        return fullName is "System.Int32" or "System.Int64" or "System.Int16"
                        or "System.UInt32" or "System.UInt64" or "System.UInt16"
                        or "System.Byte" or "System.SByte";
    }

    private static bool IsTypeArgument(CustomAttributeTypedArgument arg)
        => arg.ArgumentType.FullName == "System.Type";

    private static int? CastToInt(object? value) => value switch
    {
        int i     => i,
        long l    => checked((int)l),
        short s   => s,
        uint u    => checked((int)u),
        ulong ul  => checked((int)ul),
        ushort us => us,
        byte b    => b,
        sbyte sb  => sb,
        _         => null,
    };
}
